### ISSUE TITLE
ES6 without Babel?

### ISSUE THREAD

**Issue by lookapanda** [jellysquid3/gitlab-discord-bot#1]
```
gitlab-discord-bot/src/server.js:12
class WebhookServer {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at start (gitlab-discord-bot/src/app.js:14:17)
    at Object.<anonymous> (gitlab-discord-bot/src/app.js:9:1)
    at Module._compile (module.js:409:26)
```

Did I do something wrong or did you just not add Babel to your project yet? :P

**Comment by jellysquid3** [comment]
You may need to update your installation of NodeJS. The project is developed against v6.4.0.

**Comment by lookapanda** [comment]
Oh, I didn't knew that :P 
Well, I just forked your project and added babel... :P
