### ISSUE TITLE
Error when sending Gitlab message

### ISSUE THREAD

**Issue by tritao** [jellysquid3/gitlab-discord-bot#4]
There's an error in the bot, when you send a `!gitlab` message to the channel, the bot crashes:

```
/home/machine/gitlab-discord-bot/src/discord.js:30
    bot.sendMessage({
    ^

ReferenceError: bot is not defined
    at DiscordClient.handleMessage (/home/machine/gitlab-discord-bot/src/discord.js:30:5)
    at emitMany (events.js:127:13)
    at DiscordClient.emit (events.js:201:7)
    at DiscordClient.handleWSMessage (/home/machine/gitlab-discord-bot/node_modules/discord.io/lib/index.js:1705:11)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/home/machine/gitlab-discord-bot/node_modules/ws/lib/WebSocket.js:841:10)
    at /home/machine/gitlab-discord-bot/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/home/machine/gitlab-discord-bot/node_modules/ws/lib/Receiver.js:371:5)
    at /home/machine/gitlab-discord-bot/node_modules/ws/lib/Receiver.js:508:14
```

**Comment by Power2All** [comment]
Same issue
